# Generated by Django 2.2.1 on 2019-06-25 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_starttime',
            new_name='article_start_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_updatetime',
            new_name='article_update_time',
        ),
        migrations.RenameField(
            model_name='articlecomments',
            old_name='article_comment_starttime',
            new_name='article_comment_start_time',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_type_for_article', to='ArticleManage.ArticleType', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='articlecomments',
            name='article_comment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_for_article', to=settings.AUTH_USER_MODEL, verbose_name='文章关联'),
        ),
        migrations.AlterField(
            model_name='articlecomments',
            name='article_comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_for_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_type_type', to='ArticleManage.ArticleType', verbose_name='父菜单'),
        ),
    ]
