# Generated by Django 2.2.1 on 2019-06-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MappedManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapped',
            old_name='mapped_updatetime',
            new_name='mapped_update_time',
        ),
    ]
